name: Sync Fork
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master  # Default branch
      
      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/dataprofessor/dashboard-kit.git
          git fetch upstream
          git merge upstream/master
          git push origin master
